[tool.poetry]
name = "p6"
version = "0.1.0"
description = ""
authors = ["sabotack <sabotack.2001@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
gurobipy = "^11.0.1"
pandas = "^2.2.1"

[tool.poetry.scripts]
start = "p6.main:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
